version: "3.5"

services:
  entry_node:
    container_name: entry_node
    image: iotaledger/goshimmer
    build:
      context: ../..
    volumes:
      - ./config.entry_node.json:/config.json:ro
    ports:
      - "9000:9000/tcp" # visualizer
    expose:
      - "1888/tcp" # analysis server (within Docker network)
    networks:
      - integration-test

  peer_master:
    container_name: peer_master
    image: iotaledger/goshimmer
    build:
      context: ../..
    volumes:
      - ./config.peer_master.json:/config.json:ro
    ports:
      - "8080:8080/tcp" # web API
      - "8081:8081/tcp" # dashboard
    depends_on:
      - entry_node
    networks:
      - integration-test

  peer_replica:
    image: iotaledger/goshimmer
    build:
      context: ../..
    volumes:
      - ./config.peer_replica.json:/config.json:ro
    expose:
      - "8080/tcp" # web API (within Docker network)
    depends_on:
      - entry_node
    networks:
      - integration-test

networks:
  integration-test:
    driver: bridge
    name: integration-test
